### ISSUE TITLE
Set image properties

### ISSUE THREAD

**Issue by m-bull** [stackhpc/ansible-collection-azimuth-ops#7]
As an Azimuth operator I would like to set image properties when uploading images, such as those described in https://docs.ceph.com/en/latest/rbd/rbd-openstack/#image-properties.

Allow a `properties` key in `infra_community_images` and propagate to [Terraform](https://github.com/stackhpc/ansible-collection-azimuth-ops/blob/fe58074c2280ea9cd61a628eb8e398fb5ae2e33c/roles/infra/templates/resources.tf.j2#L2).

**Comment by mkjpryor** [comment]
Fixed by #32
